# Generated by Django 6.1.1 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_securityratelimit_userprofile_account_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('STUDENTS', 'Students'), ('ALUMNI', 'Alumni')], max_length=20),
        ),
    ]
