# Generated by Django 6.1.1 on 2026-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENTS', 'Students'), ('ALUMNI', 'Alumni')], max_length=20),
        ),
    ]
