import {useEffect,useMemo,useRef,useState} from 'react';
import {API_BASE_URL} from '../api/config';
import StaffIcon from './StaffIcon';
import './StudentSf9Card.css';
export default function OriginalSf9Card({student,documentType='SF9'}){
 const [open,setOpen]=useState(false),[images,setImages]=useState([]),[error,setError]=useState(''),dialog=useRef(null);
 const files=useMemo(()=>(student.credentialFiles||[]).filter(f=>f.title.toUpperCase().startsWith(documentType)&&/(?:Front|Back)/i.test(f.title)).sort((a,b)=>Number(/Back/i.test(a.title))-Number(/Back/i.test(b.title))),[student.credentialFiles,documentType]);
 const heading=documentType==='SF10'?'LEARNER’S PERMANENT RECORD (SF10)':'LEARNER’S PERFORMANCE REPORT';
 useEffect(()=>{if(!open)return;const controller=new AbortController(),urls=[];dialog.current.showModal();setImages([]);setError('');Promise.all(files.map(async file=>{const response=await fetch(`${API_BASE_URL}/api/operations/students/${student.id}/credentials/${file.id}/preview/`,{credentials:'include',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`Unable to load the ${documentType} card. Please retry.`);const url=URL.createObjectURL(await response.blob());urls.push(url);return {url,title:file.title};})).then(rows=>{if(!controller.signal.aborted)setImages(rows);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();urls.forEach(URL.revokeObjectURL);};},[open,student.id,files,documentType]);
 function close(){dialog.current.close();setOpen(false);}
 return <><button type="button" className="staff-primary-button" onClick={()=>setOpen(true)}>{documentType==='SF10'?'View SF10':'View original SF9'}</button><dialog ref={dialog} className="student-sf9-card-dialog" aria-label={heading} onKeyDown={e=>e.stopPropagation()} onCancel={e=>{e.preventDefault();e.stopPropagation();close();}}><header><div><h2>{heading}</h2><p>{[student.lastName,[student.firstName,student.middleName].filter(Boolean).join(' ')].filter(Boolean).join(', ')}</p></div><button type="button" aria-label={`Close ${documentType} card`} onClick={close}><StaffIcon name="fa-xmark"/></button></header>{error?<p role="alert">{error}</p>:files.length===0?<p className="student-sf9-empty">No {documentType} card attached to this student yet.</p>:images.length===0?<p role="status">Loading {documentType} card…</p>:<div className="student-sf9-card-pages">{images.map(image=><figure key={image.title}><img src={image.url} alt={image.title}/></figure>)}</div>}</dialog></>;
}
