import {useCallback,useEffect,useRef,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {usePortal} from '../hooks/PortalContext';
import {fetchCredentialQueue} from '../api/credentials';
import RequestReviewModal from './RequestReviewModal';
import StaffIcon from './StaffIcon';
import '../AdministrationDashboard.css';
import '../PrincipalDashboard.css';
const scheduledLabel = r => {
 if (!r.scheduled_release_date) return 'Not scheduled';
 const date=new Date(`${r.scheduled_release_date}T${r.scheduled_release_time||'00:00:00'}+08:00`);
 return date.toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
};
const categories=[['total','Total Requests'],['pending','Pending'],['approved','Approved'],['released','Released'],['processing','Ready for Processing'],['scheduled','Scheduled for Release'],['requested_today',"Today's Requests"],['approved_today',"Today's Approvals"],['processed_today',"Today's Processed"],['released_today',"Today's Releases"]];
export function RequestStatistics({role}){
 const system=usePortal(),navigate=useNavigate();
 return <div className={`restored-statistics ${role==='ADMIN'?'administration-dashboard':'principal-dashboard'}`}><div className={role==='ADMIN'?'stats-grid':'principal-metrics-grid'}>{categories.filter(([key])=>['total','pending','approved','released'].includes(key)).map(([key,label])=><button className={role==='ADMIN'?`stat-card ${key}`:`principal-metric-card ${key}`} key={key} onClick={()=>navigate(`${role==='ADMIN'?'/admin-credential-management':'/principal-requests'}?category=${key}`)}>{role==='ADMIN'?<><div className="stat-card-top"><div className="icon"><StaffIcon name={key.includes('released')?'fa-file-circle-check':key.includes('approved')?'fa-circle-check':key==='pending'?'fa-hourglass-half':'fa-folder-open'}/></div><span className="stat-period">Live</span></div><div className="stat-content"><h4>{label}</h4><div className="stat-value-row"><h2>{system.data.statistics?.[key]??0}</h2></div><p>View requests</p></div><div className="stat-decoration"/></>:<><div className={`metric-card-icon ${key.includes('released')?'released':key.includes('approved')?'approved':key==='pending'?'pending':''}-icon`}><StaffIcon name={key.includes('released')?'fa-file-circle-check':key.includes('approved')?'fa-circle-check':key==='pending'?'fa-hourglass-half':'fa-folder-open'}/></div><div className="metric-card-content"><span>{label}</span><strong>{system.data.statistics?.[key]??0}</strong><small>View requests</small></div></>}</button>)}</div></div>;
}
export default function RequestQueue({role='ADMIN',dashboard=false}){
 const system=usePortal(),location=useLocation(),navigate=useNavigate(),params=new URLSearchParams(location.search),category=params.get('category')||'total';
 const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(params.get('request'));
 const generation=useRef(0);
 const refresh=useCallback(async()=>{const seq=++generation.current;setError('');try{const query=new URLSearchParams(location.search);query.delete('request');query.delete('category');if(['pending','approved','released'].includes(category))query.set('status',category.toUpperCase());else if(category!=='total')query.set('category',category);const result=await fetchCredentialQueue(query.toString());if(seq===generation.current){setRows(result.requests);setLoading(false);}return result;}catch(e){if(seq===generation.current){setError(e.message);setLoading(false);}return null;}},[category,location.search]);
 useEffect(()=>{const initial=setTimeout(refresh,0),timer=setInterval(refresh,15000);return()=>{clearTimeout(initial);clearInterval(timer);generation.current++;};},[refresh]);
 useEffect(()=>{const t=setTimeout(()=>setSelected(new URLSearchParams(location.search).get('request')),0);return()=>clearTimeout(t);},[location.search]);
 const request=rows.find(r=>r.id===selected)||system.data.requests.find(r=>r.id===selected);
 const visible=rows.filter(r=>`${r.full_name} ${r.lrn} ${r.reference} ${r.credential}`.toLowerCase().includes(search.toLowerCase()));
 async function updated(){await system.refresh();return refresh();}
 return <section className="staff-panel request-queue-panel"><h1>{dashboard?(role==='PRINCIPAL'?'Principal Dashboard':'Administration Dashboard'):'Credential Requests'}</h1><p>{role==='PRINCIPAL'?'Monitor requests, releases and school activity. Administration verifies and approves credentials.':'Verify identity documents, approve requests, schedule releases and notify requesters from one queue.'}</p><RequestStatistics role={role}/><div className="staff-filters request-queue-filters"><input aria-label="Search requests" placeholder="Search name, LRN or reference" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter requests" value={category} onChange={e=>navigate(`${location.pathname}?${new URLSearchParams({...Object.fromEntries(params),category:e.target.value})}`)}>{[...categories,['ready','Ready for Release']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button type="button" className="request-queue-refresh" onClick={refresh}><StaffIcon name="fa-arrow-rotate-right"/>Refresh</button></div>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Loading requests…</p>}<div className="staff-table-wrap"><table className="staff-table request-queue-table"><caption className="request-queue-caption">{loading?'Loading requests…':`${visible.length} request${visible.length===1?'':'s'} shown`}</caption><colgroup><col style={{width:'28%'}}/><col style={{width:'20%'}}/><col style={{width:'19%'}}/><col style={{width:'23%'}}/><col style={{width:'10%'}}/></colgroup><thead><tr><th>Requester</th><th>Credential</th><th>Status / Queue</th><th>Release / Sending Schedule</th><th>Action</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.full_name}</strong><small>{r.reference}<span className="request-queue-lrn">LRN: {r.lrn}</span></small></td><td>{r.credential}<small>{r.delivery_method==='SCHOOL_TO_SCHOOL'?'Direct to school':'On site collection'}</small></td><td><span className={`staff-status staff-status-${r.status}`}>{r.status_label}</span><small>{r.status==='PENDING'?'Needs verification':r.status==='RELEASED'?'Completed':r.ready_at?'Scheduled / ready for release':'Ready for processing'}</small></td><td>{scheduledLabel(r)}<small>{r.collected_at?`Actually released: ${new Date(r.collected_at).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}`:''}</small></td><td><button onClick={()=>setSelected(r.id)}>View Request</button></td></tr>)}</tbody></table>{!loading&&visible.length===0&&<p>No requests match this filter.</p>}</div>{request&&<RequestReviewModal key={request.id} request={request} role={role} smsEnabled={system.data.sms_enabled} onUpdated={updated} onClose={()=>setSelected(null)}/>}</section>;
}
