import {useCallback,useEffect,useRef,useState} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {operation} from '../api/operations';
import './Sf9ReportCard.css';
import printStyles from './Sf9ReportCard.css?inline';
const MONTHS=['Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr'];
const emptyCard={school_head:'JOCELYN E. HEDRIANA',adviser:'',attendance:{},term_comments:{}};
export function Sf9ReportCard({recordId}){
 const [record,setRecord]=useState(null),[card,setCard]=useState(emptyCard),[grades,setGrades]=useState({}),[changed,setChanged]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false);
 const load=useCallback(async()=>{const r=await operation(`sf9/records/${recordId}/card/`);setRecord(r);setCard({...emptyCard,adviser:r.card_adviser||'',...r.card});setGrades({});setChanged(false);return r;},[recordId]);
 useEffect(()=>{let active=true;operation(`sf9/records/${recordId}/card/`).then(r=>{if(active){setRecord(r);setCard({...emptyCard,adviser:r.card_adviser||'',...r.card});setGrades({});setChanged(false);}}).catch(e=>setError(e.message));return()=>{active=false;};},[recordId]);
 const dirty=changed||Object.keys(grades).length>0;
 useEffect(()=>{if(dirty||busy)return;const timer=setInterval(()=>load().catch(()=>{}),5000);return()=>clearInterval(timer);},[load,dirty,busy]);
 function change(key,value){setCard(c=>({...c,[key]:value}));setChanged(true);setMessage('');}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const rows=Object.entries(grades).map(([key,value])=>{const [subject,term]=key.split(':').map(Number);return {subject,term,value};});const r=await operation(`sf9/records/${recordId}/card/`,{version:record.version,grades:rows,card:record.card_editable?card:{}});setRecord(r);setCard({...emptyCard,adviser:r.card_adviser||'',...r.card});setGrades({});setChanged(false);setMessage('Report card saved.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 async function print(which){setBusy(true);setError('');try{const latest=await load();const saved={...emptyCard,adviser:latest.card_adviser||'',...latest.card};const html=renderToStaticMarkup(<CardPages record={latest} card={saved} grades={{}} printMode={which}/>);const frame=document.createElement('iframe');frame.title='SF9 print preview';frame.style.cssText='position:fixed;width:1px;height:1px;left:-10000px;border:0';document.body.appendChild(frame);frame.onload=async()=>{const doc=frame.contentDocument;await Promise.all([...doc.images].map(image=>image.complete?Promise.resolve():new Promise(resolve=>{image.onload=resolve;image.onerror=resolve;})));frame.contentWindow.addEventListener('afterprint',()=>frame.remove(),{once:true});frame.contentWindow.focus();frame.contentWindow.print();};frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><title>SF9 Learner Performance Report</title><style>${printStyles}</style></head><body class="sf9-print-document">${html}</body></html>`;}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!record)return <p role={error?'alert':'status'}>{error||'Loading saved report card…'}</p>;
 return <section className="sf9-report-editor"><div className="sf9-report-toolbar"><div><strong>LEARNER’S PERFORMANCE REPORT</strong><span>{record.card_editable?'Class adviser: encode attendance and report details. Grade editing follows your assigned subject.':'Saved grades update automatically from Digital SF9.'}</span></div><div className="sf9-report-buttons"><button type="button" disabled={busy||dirty} onClick={()=>print('front')}>Print front</button><button type="button" disabled={busy||dirty} onClick={()=>print('back')}>Print back</button><button type="button" disabled={busy||dirty} onClick={()=>print('both')}>Print both pages</button></div></div><p className="sf9-report-print-note">For back-to-back printing, choose two-sided printing and flip on the long edge in your printer settings.</p>{error&&<p role="alert" className="sf9-report-error">{error}</p>}{message&&<p role="status" className="sf9-report-success">{message}</p>}<CardPages record={record} card={card} grades={grades} disabled={busy} onCardChange={change} onGradeChange={(key,value)=>{setGrades(g=>({...g,[key]:value}));setMessage('');}}/>{record.card_updated_by&&<p className="sf9-report-print-note">Last updated by {record.card_updated_by} · {new Date(record.card_updated_at).toLocaleString()}</p>}<footer className="sf9-report-footer"><button type="button" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Reload saved card</button>{(record.card_editable||record.subjects.some(s=>s.editable))&&<button type="button" disabled={busy||!dirty} onClick={save}>{busy?'Saving…':'Save report card'}</button>}{dirty&&<span>Save changes before printing.</span>}</footer></section>;
}
function Field({label,value='',onChange,disabled,printMode,type='text',maxLength=200}){return printMode?<span className="sf9-report-value">{value||' '}</span>:<input aria-label={label} type={type} value={value} maxLength={maxLength} disabled={disabled} onChange={e=>onChange?.(e.target.value)}/>;}
export function CardPages({record,card,grades={},disabled=false,onCardChange,onGradeChange,printMode}){
 const editable=record.card_editable&&!disabled&&!printMode,fullName=[record.last_name,[record.first_name,record.middle_name].filter(Boolean).join(' ')].filter(Boolean).join(', ')||record.name;
 const field=(key,label,type='text')=><Field label={label} value={card[key]||''} onChange={v=>onCardChange?.(key,v)} disabled={!editable} printMode={printMode} type={type}/>;
 const attendance=card.attendance||{},sum=key=>{const nums=MONTHS.map(m=>attendance[m]?.[key]).filter(v=>v!==undefined&&v!==null);return nums.length?nums.reduce((a,b)=>a+b,0):'';},absent=m=>attendance[m]?.class_days!=null&&attendance[m]?.present!=null?attendance[m].class_days-attendance[m].present:'';
 const age=record.birthday?(()=>{const today=new Date(),dob=new Date(record.birthday+'T00:00:00');return today.getFullYear()-dob.getFullYear()-(today.getMonth()<dob.getMonth()||(today.getMonth()===dob.getMonth()&&today.getDate()<dob.getDate())?1:0);})():'';
 return <div className={`sf9-report-pages ${printMode?'sf9-print-pages':''}`}>
 {printMode!=='back'&&<article className="sf9-report-page sf9-report-front"><header className="sf9-report-letterhead"><div className="sf9-report-deped-seal"><span>DEPARTMENT<br/>OF EDUCATION</span><b>DepEd</b></div><div>Republic of the Philippines<br/>Department of Education<br/>Region VI – Western Visayas<br/><b>SCHOOLS DIVISION OF ROXAS CITY</b><br/>Cluster II<br/>Hughes St., Tanque, Roxas City, Capiz</div><img src="/logo.png" alt="School seal"/></header><h2>PRESIDENT MANUEL ROXAS MEMORIAL INTEGRATED SCHOOL SOUTH</h2><h3>LEARNER’S PERFORMANCE REPORT</h3><p className="sf9-report-year">School Year: <u>{record.school_year}</u></p><div className="sf9-report-identity"><div><b>Name:</b><span>{fullName}</span><b>Age:</b><span>{age}</span><b>Sex:</b><span>{record.sex==='Male'?'M':record.sex==='Female'?'F':record.sex}</span></div><div><b>LRN:</b><span>{record.lrn||''}</span><b>Grade:</b><span>{record.grade.replace(/^Grade /,'')}</span><b>Section:</b><span>{record.section}</span></div></div><div className="sf9-report-letter"><p>Dear Parent/Guardian,</p><p>This Performance Report presents your child’s progress and achievement in the different learning areas.</p><p>The school welcomes you to reach out should you wish to know more about your child’s learning and performance.</p></div><div className="sf9-report-signatures"><div>{field('school_head','School head')}<span>School Head</span></div><div>{field('adviser','Class adviser')}<span>Adviser</span></div></div><h3>LEARNING PROGRESS AND ACHIEVEMENT</h3><table className="sf9-report-grade-table"><thead><tr><th rowSpan="2">Learning Areas</th><th colSpan="3">TERM</th><th rowSpan="2">Final<br/>Grade</th><th rowSpan="2">Remarks</th></tr><tr>{[1,2,3].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{record.subjects.map(s=><tr key={s.id}><th scope="row">{s.name==='GMRC'?'GMRC (Good Manners and Right Conduct)':s.name==='EPP'?'TLE / EPP':s.name}</th>{s.terms.map((g,i)=>{const key=`${s.id}:${i+1}`,value=grades[key]??g?.value??'';return <td key={i}>{printMode?<span>{value}</span>:<input type="number" min="0" max="100" step="0.01" aria-label={`${s.name} report Term ${i+1}`} value={value} disabled={!s.editable||disabled||Boolean(printMode)} onChange={e=>onGradeChange?.(key,e.target.value)}/>}</td>})}<td>{s.final?.value||''}</td><td>{s.final?.value!=null?(Number(s.final.value)>=75?'Passed':'Failed'):''}</td></tr>)}<tr><th colSpan="4" className="sf9-report-average">General Average</th><td>{record.general_average||''}</td><td/></tr></tbody></table><h4>PERFORMANCE INDICATORS</h4><table className="sf9-report-indicators"><thead><tr><th>Grading Scale</th><th>Description</th><th>Remarks</th></tr></thead><tbody>{[['90–100','Advancing','Passed'],['80–89','Benchmarking','Passed'],['75–79','Connecting','Passed'],['65–74','Developing','Failed'],['0–64','Emerging','Failed']].map(row=><tr key={row[0]}>{row.map(v=><td key={v}>{v}</td>)}</tr>)}</tbody></table></article>}
 {printMode!=='front'&&<article className="sf9-report-page sf9-report-back"><h3>ATTENDANCE RECORD</h3><table className="sf9-report-attendance"><thead><tr><th>Month</th>{MONTHS.map(m=><th key={m}>{m}</th>)}<th>Total</th></tr></thead><tbody>{[['class_days','No. of Class Days'],['present','No. of Days Present'],['absent','No. of Days Absent']].map(([key,label])=><tr key={key}><th>{label}</th>{MONTHS.map(m=><td key={m}>{key==='absent'?absent(m):printMode?(attendance[m]?.[key]??''):<input type="number" min="0" max="31" step="1" aria-label={`${m} ${label}`} disabled={!editable} value={attendance[m]?.[key]??''} onChange={e=>onCardChange?.('attendance',{...attendance,[m]:{...attendance[m],[key]:e.target.value===''?null:Number(e.target.value)}})}/>}</td>)}<td>{key==='absent'?(MONTHS.some(m=>absent(m)!=='')?MONTHS.reduce((n,m)=>n+(absent(m)||0),0):''):sum(key)}</td></tr>)}</tbody></table><div className="sf9-report-comments">{[1,2,3].map(term=>{const value=card.term_comments?.[term]??record.teacher_comments.filter(c=>c.term===term&&c.message).map(c=>`${c.message} (${c.subject})`).join('\n');return <section key={term}><b>Term {term}</b>{printMode?<p>{value}</p>:<textarea aria-label={`Report card Term ${term} comment`} maxLength={2000} value={value} disabled={!editable} onChange={e=>onCardChange?.('term_comments',{...card.term_comments,[term]:e.target.value})}/>}</section>})}</div><div className="sf9-report-parent-signatures">{[1,2,3].map(n=><label key={n}>Term {n}{field(`parent_term_${n}`,`Term ${n} parent acknowledgement`)}</label>)}</div><div className="sf9-report-admission"><label>Admitted to Grade:{field('admitted_grade','Admitted to grade')}</label><label>Eligible for Admission to Grade:{field('eligible_grade','Eligible for admission to grade')}</label><label>Approved:{field('approved','Approved promotion details')}</label></div><div className="sf9-report-signatures"><div>{field('school_head','Back school head')}<span>School Head</span></div><div>{field('adviser','Back adviser')}<span>Adviser</span></div></div><div className="sf9-report-admission sf9-report-final-admission"><label>Admitted in:{field('admitted_in','Admitted in')}</label><label>Date:{field('admission_date','Admission date','date')}</label></div><div className="sf9-report-signatures"><div><span className="sf9-report-signature-line"/><span>School Head</span></div></div></article>}
 </div>;
}
