# Generated by Django 6.1.1 on 2026-10-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_final_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='GradingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 3)), name='sf9_three_terms')],
            },
        ),
        migrations.CreateModel(
            name='Sf9Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sf9_records', to='operations.studentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Sf9Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.gradingterm')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='operations.sf9record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Sf9FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='operations.sf9record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.gradelevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('grade_level', 'name'), name='unique_grade_section'),
        ),
        migrations.AddConstraint(
            model_name='sf9record',
            constraint=models.UniqueConstraint(fields=('student', 'school_year'), name='unique_student_sf9_year'),
        ),
        migrations.AddConstraint(
            model_name='sf9grade',
            constraint=models.UniqueConstraint(fields=('record', 'subject', 'term'), name='unique_sf9_subject_term'),
        ),
        migrations.AddConstraint(
            model_name='sf9grade',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 100)), name='valid_sf9_grade'),
        ),
        migrations.AddConstraint(
            model_name='sf9finalgrade',
            constraint=models.UniqueConstraint(fields=('record', 'subject'), name='unique_sf9_subject_final'),
        ),
        migrations.AddConstraint(
            model_name='sf9finalgrade',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 100)), name='valid_sf9_final'),
        ),
    ]
