# Generated by Django 6.1.1 on 2026-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_sf9_reference_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='lrn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
