# Generated by Django 6.1.1 on 2026-10-06 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_studentrecord_lrn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='operations.sf9record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.gradingterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'teacher', 'term'), name='unique_teacher_comment_term')],
            },
        ),
    ]
