# Generated by Django 6.1.1 on 2026-10-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_sf9reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='is_adviser',
            field=models.BooleanField(default=False),
        ),
    ]
