# Generated by Django 6.1.1 on 2026-10-07 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_teacherassignment_is_adviser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_adviser', True)), fields=('section',), name='one_adviser_per_section'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_adviser', False), ('section__isnull', False), _connector='OR'), name='adviser_requires_section'),
        ),
    ]
