# Generated by Django 6.1.1 on 2026-10-07 10:38

from django.conf import settings
from django.db import migrations, models


def restore_started_terms(apps, schema_editor):
    Grade=apps.get_model('operations','Sf9Grade')
    Record=apps.get_model('operations','Sf9Record')
    alias=schema_editor.connection.alias
    for term in [2,3]:
        Record.objects.using(alias).filter(pk__in=Grade.objects.using(alias).filter(term__number=term).values('record_id')).update(started_term=term)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_teacherassignment_one_adviser_per_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sf9grade',
            name='valid_sf9_grade',
        ),
        migrations.AddField(
            model_name='sf9grade',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sf9record',
            name='started_term',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sf9grade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RunPython(restore_started_terms,migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sf9grade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_incomplete', True), ('value__isnull', True)), models.Q(('is_incomplete', False), ('value__gte', 0), ('value__isnull', False), ('value__lte', 100)), _connector='OR'), name='valid_sf9_grade'),
        ),
    ]
