export const approved = r => Boolean(r.approved_at);
export const statusName = r => ({SUBMITTED:'Pending',PREPARING:'Preparing',PRINCIPAL_REVIEW:'Pending approval',PRINCIPAL_APPROVED:'Approved',READY:'Ready for pickup',COLLECTED:'Released',RETURNED:'Returned',UNAVAILABLE:'Unavailable'}[r.status] || r.status);
export const localDay = v => {const d=new Date(v);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
export const elapsed = r => r.collected_at ? Math.max(0,(new Date(r.collected_at)-new Date(r.created_at))/86400000) : null;
export function metrics(items){const complete=items.filter(r=>r.status==='COLLECTED');return {total:items.length,pending:items.filter(r=>!['COLLECTED','READY','PRINCIPAL_APPROVED'].includes(r.status)).length,approved:items.filter(approved).length,ready:items.filter(r=>r.status==='READY').length,released:complete.length,average:complete.length?(complete.reduce((n,r)=>n+elapsed(r),0)/complete.length).toFixed(1):'—'};}
export function auditRows(data){return [...(data.audit||[]).map(e=>({...e,description:e.detail,target:e.object_id,role:({ADMIN:'Administrator',PRINCIPAL:'Principal',ICT:'ICT Personnel'})[e.role]||e.role})),...(data.requests||[]).flatMap(r=>(r.events||[]).map((e,i)=>({...e,id:r.id+':'+i,module:'Credentials',description:e.note||r.status_label,target:r.id+' · '+r.full_name,student:r.full_name,requestId:r.id,role:['approve','return'].includes(e.action)?'Principal':e.action==='submitted'?'Requester':'Administrator'})))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(e=>({...e,date:localDay(e.created_at),time:new Date(e.created_at).toLocaleTimeString(),level:'Success',ip:'Not recorded',icon:'fa-clock-rotate-left'}));}
export function monthlyCounts(items){return Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const group=items.filter(r=>new Date(r.created_at).getMonth()===d.getMonth()&&new Date(r.created_at).getFullYear()===d.getFullYear());const m=metrics(group);return {m:d.toLocaleDateString(undefined,{month:'short'}),p:group.filter(r=>['SUBMITTED','PREPARING','PRINCIPAL_REVIEW'].includes(r.status)).length,a:group.filter(r=>['READY','PRINCIPAL_APPROVED'].includes(r.status)).length,r:m.released,x:group.filter(r=>['RETURNED','UNAVAILABLE'].includes(r.status)).length};});}

export function ictSnapshot(d){return {...d,settings:{...d.settings,displayName:d.user.name,email:d.user.email,...d.preferences},activeUsers:d.accounts.filter(a=>a.status==='Active').length,pendingAccess:0,accessRequests:[],backupStatus:'Not configured',nextBackup:'Not scheduled',lastBackup:null,uptime:'Not monitored',responseTime:'Live connectivity check',storageUsedGB:null,storageTotalGB:null,backupConfigured:false,storageGB:0,totalGB:0,maintenance:d.tasks.map(t=>({...t,detail:t.notes,done:t.status==='Completed'})),events:d.audit.map(e=>({id:e.id,title:e.action,detail:e.detail,time:new Date(e.created_at).toLocaleString(),createdAt:e.created_at})),audit:d.audit.map(e=>({id:e.id,title:e.action,detail:e.detail,createdAt:e.created_at})),controls:[{id:'audit',name:'Transaction audit trail',detail:'Saved workflow and staff actions',status:'Enabled'},{id:'role',name:'Role permissions',detail:'Enforced by Django for each operation',status:'Enabled'},{id:'backup',name:'Off-device backups',detail:'Deployment storage and backup scheduler are not configured',status:'Pending'}],policy:{frequency:'Not configured',time:'',retention:0,destination:'Not configured'},security:{mfaEnabled:false,lastPasswordChange:'Not recorded'}};}
