# Generated by Django 6.1.1 on 2026-09-26 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_key', models.UUIDField(unique=True)),
                ('requester_type', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], max_length=10)),
                ('full_name', models.CharField(max_length=160)),
                ('lrn', models.CharField(max_length=12)),
                ('grade_level', models.CharField(blank=True, max_length=40)),
                ('section', models.CharField(blank=True, max_length=80)),
                ('graduation_year', models.CharField(blank=True, max_length=4)),
                ('credential', models.CharField(max_length=160)),
                ('purpose', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('additional_details', models.CharField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PREPARING', 'Preparing'), ('UNAVAILABLE', 'Unavailable / needs information'), ('PRINCIPAL_REVIEW', 'Awaiting principal approval'), ('RETURNED', 'Returned for correction'), ('PRINCIPAL_APPROVED', 'Principal approved'), ('READY', 'Ready for release'), ('COLLECTED', 'Collected')], db_index=True, default='SUBMITTED', max_length=24)),
                ('version', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credentials', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_credentials', to=settings.AUTH_USER_MODEL)),
                ('release_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_confirmed_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='credentials.credentialrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=480)),
                ('status', models.CharField(default='QUEUED', max_length=24)),
                ('provider_id', models.CharField(blank=True, max_length=80)),
                ('provider_status', models.CharField(blank=True, max_length=40)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='credentials.credentialrequest')),
            ],
        ),
    ]
