# Generated by Django 6.1.1 on 2026-09-29 14:54

import credentials.documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='delivery_method',
            field=models.CharField(choices=[('ON_SITE', 'Claimed On Site'), ('SCHOOL_TO_SCHOOL', 'School-to-School')], default='ON_SITE', max_length=20),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='receiving_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='reference',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='verification_document',
            field=models.FileField(blank=True, storage=credentials.documents.PrivateDocumentStorage(), upload_to=credentials.documents.document_path),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='verification_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='credentialrequest',
            name='full_name',
            field=models.CharField(max_length=242),
        ),
    ]
