# Generated by Django 6.1.1 on 2026-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_backfill_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Pending Administration Verification'), ('PREPARING', 'Preparing'), ('UNAVAILABLE', 'Unavailable / needs information'), ('PRINCIPAL_REVIEW', 'Awaiting principal approval'), ('RETURNED', 'Returned for correction'), ('PRINCIPAL_APPROVED', 'Student Information Approved'), ('READY', 'Ready for release'), ('COLLECTED', 'Released'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=24),
        ),
    ]
