# Generated by Django 6.1.1 on 2026-09-29 15:50

import credentials.documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_credentialrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialrequest',
            name='id_document',
            field=models.FileField(blank=True, storage=credentials.documents.PrivateDocumentStorage(), upload_to=credentials.documents.document_path),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='id_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='psa_document',
            field=models.FileField(blank=True, storage=credentials.documents.PrivateDocumentStorage(), upload_to=credentials.documents.document_path),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='psa_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
