# Generated by Django 6.1.1 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_current_school_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialrequest',
            name='scheduled_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='scheduled_release_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RELEASED', 'Released')], db_index=True, default='PENDING', max_length=24),
        ),
    ]
