# Generated by Django 6.1.1 on 2026-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_credentialrequest_scheduled_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='provider',
            field=models.CharField(default='SEMAPHORE', max_length=16),
        ),
    ]
