import StaffIcon from './components/StaffIcon';
import TeacherAssignmentFields from './components/TeacherAssignmentFields';
import './components/Sf9.css';
import {useRef,useState} from 'react';
import {usePortal} from './hooks/PortalContext';

const empty={name:'',email:'',username:'',role:'Administrator',password:'',assignment:{},status:'Active'};
export default function PrincipalUserAccess({role:actorRole="PRINCIPAL"}){
 const system=usePortal(),accounts=(actorRole==='ADMIN'?system.data.teacher_accounts:system.data.accounts)||[],[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[role,setRole]=useState('All'),[action,setAction]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState(empty),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false);
 const statuses=['All','Active','Inactive','Temporarily Locked','Permanently Locked'];
 const visible=accounts.filter(a=>(filter==='All'||a.status===filter)&&(role==='All'||a.role===role)&&`${a.name} ${a.username} ${a.email}`.toLowerCase().includes(search.toLowerCase()));
 function open(type,account=null){setSelected(account);setForm(account?{...empty,...account,password:''}:{...empty,role:actorRole==='ADMIN'?'Teacher':'Administrator'});setError('');setSuccess('');setAction(type);}
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await system.mutate('accounts/',{action,values:{...form,id:selected?.id}});setAction(null);setSuccess('Account updated successfully.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <section className="staff-panel"><h1>{actorRole==='ADMIN'?'Teacher Accounts':'User Access'}</h1><p>{actorRole==='ADMIN'?'Manage teacher accounts and teaching assignments.':'View and manage school personnel accounts.'}</p><div className="staff-statistics">{statuses.map(status=><button className="staff-stat" key={status} onClick={()=>setFilter(status)}><span>{status==='All'?'Total Accounts':status}</span><strong>{accounts.filter(a=>status==='All'||a.status===status).length}</strong></button>)}</div><div className="staff-filters"><input aria-label="Search accounts" placeholder="Search name, username or email" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Account status" value={filter} onChange={e=>setFilter(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Account role" value={role} onChange={e=>setRole(e.target.value)}>{(actorRole==='ADMIN'?['All','Teacher']:['All','Administrator','Principal','Teacher']).map(s=><option key={s}>{s}</option>)}</select><button className="staff-primary-button" onClick={()=>open('create')}>Create Account</button></div>{success&&<p role="status">{success}</p>}<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Personnel</th><th>Role</th><th>Assignment</th><th>Status</th><th>Last Sign In</th><th>Manage</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.username} · {a.email}</small></td><td>{a.role}</td><td>{a.assignment?<><strong>{a.assignment.subject_name}</strong>{a.assignment.is_adviser&&<small><b>Class adviser</b></small>}<small>{a.assignment.grade_name} · {a.assignment.section_name}</small></>:'—'}</td><td>{a.status}</td><td>{a.lastSignIn==='Not yet signed in'?a.lastSignIn:new Date(a.lastSignIn).toLocaleString()}</td><td>{a.id===system.data.user.id?<small>Your account</small>:<><button onClick={()=>open('edit',a)}>Edit</button> <button onClick={()=>open('reset',a)}>Reset Password</button> <button onClick={()=>open(a.status==='Inactive'?'activate':'deactivate',a)}>{a.status==='Inactive'?'Activate':'Deactivate'}</button> {a.lock_status!=='Active'&&<button onClick={()=>open('unlock',a)}>Unlock</button>}</>}</td></tr>)}</tbody></table>{visible.length===0&&<p>No accounts match your filters.</p>}</div>{action&&<AccountDialog actorRole={actorRole} action={action} selected={selected} form={form} setForm={setForm} save={save} error={error} busy={busy} onClose={()=>setAction(null)}/>}</section>;
}
function AccountDialog({actorRole,action,selected,form,setForm,save,error,busy,onClose}){
 const dialog=useRef(null);
 const [showPassword,setShowPassword]=useState(false);
 const titles={create:'Create Account',edit:'Edit Account',reset:'Reset Password',activate:'Activate Account',deactivate:'Deactivate Account',unlock:'Unlock Account'};
 function set(key,value){setForm(previous=>({...previous,[key]:value}));}
 return <dialog className="request-review-modal staff-account-dialog" ref={el=>{dialog.current=el;if(el&&!el.open)el.showModal();}} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form className="staff-panel issue-form staff-account-form" onSubmit={save}><header className="staff-account-dialog-header"><h2>{titles[action]}</h2></header><div className="staff-account-dialog-body">{selected&&<p>{selected.name} · {selected.username}</p>}{['create','edit'].includes(action)&&<><label>Full Name<input required maxLength={150} value={form.name} onChange={e=>set('name',e.target.value)}/></label>{(action==='create'||form.role==='Teacher')&&<><label>Username<input required maxLength={150} value={form.username} onChange={e=>set('username',e.target.value)}/></label><label>Email<input type="email" required value={form.email} onChange={e=>set('email',e.target.value)}/></label></>}<label>Role<select value={form.role} onChange={e=>set('role',e.target.value)}>{actorRole!=='ADMIN'&&<><option>Administrator</option><option>Principal</option></>}<option>Teacher</option></select></label>{form.role==='Teacher'&&<><TeacherAssignmentFields canAssignAdviser={actorRole==='PRINCIPAL'} value={form.assignment||{}} onChange={value=>set('assignment',value)}/><label>Account status<select value={form.status==='Inactive'?'Inactive':'Active'} onChange={e=>set('status',e.target.value)}><option>Active</option><option>Inactive</option></select></label></>}</>}{['create','reset'].includes(action)&&<label>Password<span className="staff-account-password"><input type={showPassword?"text":"password"} required maxLength={256} autoComplete="new-password" value={form.password} onChange={e=>set('password',e.target.value)}/><button type="button" className="staff-account-password-toggle" aria-label={showPassword?"Hide password":"Show password"} aria-pressed={showPassword} onClick={()=>setShowPassword(value=>!value)}><StaffIcon name={showPassword?"fa-eye-slash":"fa-eye"}/></button></span></label>}{action==='unlock'&&<p>Reset the login lock and failed attempt counter.</p>}{error&&<p role="alert">{error}</p>}</div><footer className="staff-account-dialog-footer"><button type="submit" className="staff-account-confirm" disabled={busy}>{busy?'Saving…':'Confirm'}</button><button className="staff-account-cancel" type="button" disabled={busy} onClick={onClose}>Cancel</button></footer></form></dialog>;
}
