import {useRef,useState} from 'react';
import {usePortal} from './hooks/PortalContext';

const empty={name:'',email:'',username:'',role:'Administrator',password:''};
export default function PrincipalUserAccess(){
 const system=usePortal(),accounts=system.data.accounts||[],[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[role,setRole]=useState('All'),[action,setAction]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState(empty),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false);
 const statuses=['All','Active','Inactive','Temporarily Locked','Permanently Locked'];
 const visible=accounts.filter(a=>(filter==='All'||a.status===filter)&&(role==='All'||a.role===role)&&`${a.name} ${a.username} ${a.email}`.toLowerCase().includes(search.toLowerCase()));
 function open(type,account=null){setSelected(account);setForm(account?{...empty,...account,password:''}:empty);setError('');setSuccess('');setAction(type);}
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await system.mutate('accounts/',{action,values:{...form,id:selected?.id}});setAction(null);setSuccess('Account updated successfully.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <section className="staff-panel"><h1>User Access</h1><p>View and manage school personnel accounts. All changes are recorded in the audit log.</p><div className="staff-statistics">{statuses.map(status=><button className="staff-stat" key={status} onClick={()=>setFilter(status)}><span>{status==='All'?'Total Accounts':status}</span><strong>{accounts.filter(a=>status==='All'||a.status===status).length}</strong></button>)}</div><div className="staff-filters"><input aria-label="Search accounts" placeholder="Search name, username or email" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Account status" value={filter} onChange={e=>setFilter(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Account role" value={role} onChange={e=>setRole(e.target.value)}>{['All','Administrator','Principal'].map(s=><option key={s}>{s}</option>)}</select><button className="staff-primary-button" onClick={()=>open('create')}>Create Account</button></div>{success&&<p role="status">{success}</p>}<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Personnel</th><th>Role</th><th>Status</th><th>Last Sign In</th><th>Manage</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.username} · {a.email}</small></td><td>{a.role}</td><td>{a.status}</td><td>{a.lastSignIn==='Not yet signed in'?a.lastSignIn:new Date(a.lastSignIn).toLocaleString()}</td><td>{a.id===system.data.user.id?<small>Your account</small>:<><button onClick={()=>open('edit',a)}>Edit</button> <button onClick={()=>open('reset',a)}>Reset Password</button> <button onClick={()=>open(a.status==='Inactive'?'activate':'deactivate',a)}>{a.status==='Inactive'?'Activate':'Deactivate'}</button> {a.lock_status!=='Active'&&<button onClick={()=>open('unlock',a)}>Unlock</button>}</>}</td></tr>)}</tbody></table>{visible.length===0&&<p>No accounts match your filters.</p>}</div>{action&&<AccountDialog action={action} selected={selected} form={form} setForm={setForm} save={save} error={error} busy={busy} onClose={()=>setAction(null)}/>}</section>;
}
function AccountDialog({action,selected,form,setForm,save,error,busy,onClose}){
 const dialog=useRef(null);
 const titles={create:'Create Account',edit:'Edit Account',reset:'Reset Password',activate:'Activate Account',deactivate:'Deactivate Account',unlock:'Unlock Account'};
 function set(key,value){setForm(previous=>({...previous,[key]:value}));}
 return <dialog className="request-review-modal" ref={el=>{dialog.current=el;if(el&&!el.open)el.showModal();}} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form className="staff-panel issue-form" onSubmit={save}><h2>{titles[action]}</h2>{selected&&<p>{selected.name} · {selected.username}</p>}{['create','edit'].includes(action)&&<><label>Full Name<input required maxLength={150} value={form.name} onChange={e=>set('name',e.target.value)}/></label>{action==='create'&&<><label>Username<input required maxLength={150} value={form.username} onChange={e=>set('username',e.target.value)}/></label><label>Email<input type="email" required value={form.email} onChange={e=>set('email',e.target.value)}/></label></>}<label>Role<select value={form.role} onChange={e=>set('role',e.target.value)}><option>Administrator</option><option>Principal</option></select></label></>}{['create','reset'].includes(action)&&<label>Password<input type="password" required maxLength={256} autoComplete="new-password" value={form.password} onChange={e=>set('password',e.target.value)}/></label>}{action==='unlock'&&<p>Reset the login lock and failed attempt counter.</p>}{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'Saving…':'Confirm'}</button><button type="button" disabled={busy} onClick={onClose}>Cancel</button></form></dialog>;
}
