import {useNavigate} from 'react-router-dom';
import {Fragment,useCallback,useEffect,useState} from 'react';
import {operation} from './api/operations';
import {usePortal} from './hooks/PortalContext';
import {Sf9Editor} from './components/Sf9Editor';
import './components/Sf9.css';
const sexGroup=r=>['male','m'].includes(String(r.sex).toLowerCase())?'Male':['female','f'].includes(String(r.sex).toLowerCase())?'Female':'Unspecified';
const groupOrder={Male:0,Female:1,Unspecified:2};
export default function Sf9Workspace({role}){
 const navigate=useNavigate();
 const openRecord=r=>role==='TEACHER'?navigate(`/teacher-digital-sf9?record=${r.id}`):setSelected(r);
 const system=usePortal(),[catalog,setCatalog]=useState(null),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[filters,setFilters]=useState({year:'',grade:'',section:''}),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;operation('sf9/catalog/').then(c=>{if(active)setCatalog(c);}).catch(e=>setError(e.message));return()=>{active=false;};},[]);
 const refresh=useCallback(async()=>{try{const query=new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)));const result=await operation(`sf9/records/?${query}`);setRows(result.records);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}},[filters]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[refresh]);
 const a=system.data.assignment;const visible=rows.filter(r=>`${r.name} ${r.lrn||'LRN not yet assigned'}`.toLowerCase().includes(search.toLowerCase())).sort((x,y)=>groupOrder[sexGroup(x)]-groupOrder[sexGroup(y)]||(x.last_name||x.name).localeCompare(y.last_name||y.name,'en',{sensitivity:'base'})||(x.first_name||x.name).localeCompare(y.first_name||y.name,'en',{sensitivity:'base'}));const subjects=catalog?.subjects||[];
 return <section className="staff-panel sf9-workspace"><header className="sf9-heading"><div><span>STUDENT RECORDS</span><h1>SF9 Gradebook</h1><p>Final Grades and General Average</p></div></header>{role==='TEACHER'&&<div className="sf9-assignment">{a?<><div><small>ASSIGNED SUBJECT</small><strong>{a.subject_name}</strong></div><div><small>CLASS</small><strong>{a.grade_name} · {a.section_name}</strong></div></>:<strong>No teaching assignment. Contact Administration.</strong>}</div>}
 <div className="sf9-filter-panel"><div className="staff-filters"><input aria-label="Search learners" placeholder="Search student or LRN" value={search} onChange={e=>setSearch(e.target.value)}/><label className="sf9-filter-label">School year<select aria-label="School year" value={filters.year} onChange={e=>setFilters(f=>({...f,year:e.target.value}))}><option value="">All school years</option>{catalog?.school_years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label>{role==='ADMIN'&&<><label className="sf9-filter-label">Grade level<select aria-label="Grade level" value={filters.grade} onChange={e=>setFilters(f=>({...f,grade:e.target.value,section:''}))}><option value="">All grade levels</option>{catalog?.grade_levels.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="sf9-filter-label">Section<select aria-label="Section" value={filters.section} onChange={e=>setFilters(f=>({...f,section:e.target.value}))}><option value="">All sections</option>{catalog?.sections.filter(s=>!filters.grade||s.grade_level_id===Number(filters.grade)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></>}<button className="sf9-refresh-button" onClick={refresh}>Refresh</button></div></div>
 <div className="sf9-sheet-toolbar"><div><strong>{visible.length} learner{visible.length===1?'':'s'}</strong><span>Select a name to open the SF9.</span></div><div className="sf9-legend"><span><i className="editable"/>Editable grades</span><span><i/>Read-only</span></div></div><p className="sf9-sheet-hint">Scroll sideways to view all subjects. General average remains blank.</p>{error&&<p role="alert" className="staff-error">{error}</p>}{loading?<p role="status">Loading saved SF9 records…</p>:<div className="sf9-sheet-wrap"><table className="sf9-sheet"><thead><tr><th rowSpan="3" className="sf9-learner-col">Names of Learners</th>{subjects.map(s=><th colSpan="4" key={s.id} className={a?.subject===s.id?'assigned':''}>{s.name}</th>)}<th rowSpan="3">Gen.<br/>Average</th><th rowSpan="3">SF9</th></tr><tr>{subjects.map(s=><Fragment key={s.id}><th key={`${s.id}-term`} colSpan="3">Term</th><th key={`${s.id}-final`} rowSpan="2">Final<br/>Grade</th></Fragment>)}</tr><tr>{subjects.flatMap(s=>[1,2,3].map(n=><th key={`${s.id}-${n}`}>{n}</th>))}</tr></thead><tbody>{visible.map((r,index)=><Fragment key={r.id}>{(index===0||sexGroup(visible[index-1])!==sexGroup(r))&&<tr className="sf9-group-heading"><th className="sf9-learner-col" scope="row">{sexGroup(r)==='Male'?'MALE':sexGroup(r)==='Female'?'FEMALE':'SEX NOT SPECIFIED'}</th><td colSpan={subjects.length*4+2}/></tr>}<tr><th className="sf9-learner-col" scope="row"><button onClick={()=>openRecord(r)}><strong>{r.name}</strong><small>{r.lrn||'LRN not yet assigned'} · {r.grade} / {r.section}<br/>SY {r.school_year}</small></button></th>{subjects.flatMap(s=>{const row=r.subjects.find(x=>x.id===s.id);return [...[1,2,3].map(n=><td key={`${s.id}-${n}`} className={role==='TEACHER'&&row?.editable?'sf9-sheet-editable':''}>{row?.terms[n-1]?.value??'—'}</td>),<td key={`${s.id}-final`}>{row?.final?.value??'—'}</td>];})}<td>{r.general_average??'—'}</td><td><button className="sf9-open-button" onClick={()=>openRecord(r)}>{role==='TEACHER'?'Open digital SF9':'View SF9'}</button></td></tr></Fragment>)}</tbody></table>{visible.length===0&&<p>No applicable records. Administration must save each student’s grade level, section and school year.</p>}</div>}
 {rows.length===500&&<p>Showing up to 500 records. Select a class and school year to narrow the list.</p>}
 {selected&&<dialog className="sf9-dialog" ref={el=>{if(el&&!el.open)el.showModal();}} onCancel={e=>{e.preventDefault();setSelected(null);}}><Sf9Editor key={selected.id} record={selected} role={role} onSaved={saved=>{setRows(previous=>previous.map(row=>row.id===saved.id?saved:row));setSelected(saved);refresh();}} onClose={()=>setSelected(null)}/></dialog>}
 </section>;
}
