import {useCallback,useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {operation} from './api/operations';
import {usePortal} from './hooks/PortalContext';
import {Sf9Editor} from './components/Sf9Editor';
import './components/Sf9.css';
export default function TeacherStudentRecords(){
 const portal=usePortal(),navigate=useNavigate(),[rows,setRows]=useState([]),[search,setSearch]=useState(''),[year,setYear]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const r=await operation('sf9/records/');setRows(r.records);}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
 useEffect(()=>{refresh();},[refresh]);
 const a=portal.data.assignment,visible=rows.filter(r=>(!year||r.school_year===year)&&`${r.name} ${r.lrn||''}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>a.last_name.localeCompare(b.last_name)||a.first_name.localeCompare(b.first_name));
 return <section className="staff-panel"><header className="sf9-heading"><div><span>TEACHER PORTAL</span><h1>Student Records</h1><p>View your class and update only your assigned subject.</p></div></header><div className="sf9-assignment"><div><small>ASSIGNED CLASS</small><strong>{a?`${a.grade_name} · ${a.section_name}`:'No assignment'}</strong></div><div><small>SUBJECT</small><strong>{a?.subject_name||'Contact the Principal'}</strong></div></div><div className="sf9-filter-panel"><div className="staff-filters"><label className="sf9-filter-label">Search student<input placeholder="Search name or LRN" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="sf9-filter-label">School year<select value={year} onChange={e=>setYear(e.target.value)}><option value="">All school years</option>{[...new Set(rows.map(r=>r.school_year))].map(y=><option key={y}>{y}</option>)}</select></label><button type="button" className="sf9-refresh-button" disabled={loading} onClick={refresh}>{loading?'Loading…':'Refresh records'}</button></div></div>{error&&<p role="alert">{error} Use Refresh records to try again.</p>}<h2 className="teacher-records-title">Student List <small>{visible.length} records</small></h2><div className="teacher-records-table-wrap"><table className="teacher-records-table"><thead><tr><th>LRN</th><th>Student name</th><th>Grade / Section</th><th>Sex</th><th>School year</th><th>Actions</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.lrn||'Not yet assigned'}</td><td><strong>{r.last_name}, {r.first_name} {r.middle_name}</strong></td><td>{r.grade} / {r.section}</td><td>{r.sex||'—'}</td><td>{r.school_year}</td><td><div className="teacher-records-actions"><button className="sf9-open-button" onClick={()=>setSelected(r)}>View / Enter grades</button><button className="sf9-open-button" onClick={()=>navigate(`/teacher-sf9-report?record=${r.id}`)}>SF9</button></div></td></tr>)}</tbody></table>{loading?<p role="status">Loading student records…</p>:!error&&!visible.length&&<p>{a?'No matching assigned students.':'No teaching assignment. Contact the Principal to assign your class and subject.'}</p>}</div>{selected&&<dialog className="sf9-dialog" ref={el=>{if(el&&!el.open)el.showModal();}} onCancel={e=>{e.preventDefault();setSelected(null);}}><Sf9Editor record={selected} role="TEACHER" onClose={()=>setSelected(null)} onSaved={saved=>{setSelected(saved);setRows(old=>old.map(r=>r.id===saved.id?saved:r));}}/></dialog>}</section>;
}
