import {useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {loginUser} from './auth/session';
import EntryBrand from './EntryBrand';
import './AdministrationLogin.css';
import './EntryTheme.css';
import './PasswordRecovery.css';
export default function TeacherLogin(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false),navigate=useNavigate();
 async function submit(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await loginUser(username.trim(),password,'TEACHER');if(!result.authenticated||result.user?.role!=='TEACHER')throw new Error('Please sign in with your teacher account.');navigate('/teacher-student-records',{replace:true});}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <div className="admin-login-page entry-page recovery-page"><main className="admin-login-main"><section className="admin-login-card entry-card"><aside className="recovery-branding"><EntryBrand/><div className="recovery-brand-copy"><span>TEACHER PORTAL</span><h2>Your class.<br/>Your subject.</h2><p>Secure digital SF9 grade entry.</p></div></aside><div className="recovery-content"><span className="recovery-eyebrow">SCHOOL PERSONNEL</span><h1>Teacher sign in</h1><p className="recovery-intro">Use the account assigned by Administration.</p><form className="admin-login-form" onSubmit={submit}><div className="admin-field"><label htmlFor="teacher-username">Username</label><i className="fa-regular fa-user" aria-hidden="true"/><input id="teacher-username" autoComplete="username" required maxLength={150} value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="admin-field"><label htmlFor="teacher-password">Password</label><i className="fa-solid fa-lock" aria-hidden="true"/><input id="teacher-password" type={show?'text':'password'} autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></div><label style={{fontSize:12}}><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show password</label>{error&&<p role="alert">{error}</p>}<button className="admin-login-button" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><Link className="recovery-back" to="/forgot-password">Forgot password?</Link><Link className="recovery-back" to="/login/school">← Back to staff selection</Link></div></section></main></div>;
}
